# Hardware resources for the REEM-C robot.

joints:
        - leg_left_1_joint
        - leg_left_2_joint
        - leg_left_3_joint
        - leg_left_4_joint
        - leg_left_5_joint
        - leg_left_6_joint
        - leg_right_1_joint
        - leg_right_2_joint
        - leg_right_3_joint
        - leg_right_4_joint
        - leg_right_5_joint
        - leg_right_6_joint
        - torso_1_joint
        - torso_2_joint
        - arm_left_1_joint
        - arm_left_2_joint
        - arm_left_3_joint
        - arm_left_4_joint
        - arm_left_5_joint
        - arm_left_6_joint
        - arm_left_7_joint
        - arm_right_1_joint
        - arm_right_2_joint
        - arm_right_3_joint
        - arm_right_4_joint
        - arm_right_5_joint
        - arm_right_6_joint
        - arm_right_7_joint
        - head_1_joint
        - head_2_joint
    
ft_sensors:     
        - left_ankle_ft
        - right_ankle_ft

ft_sensors_calib:
        - [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
        - [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]

imu_sensor:    base_imu

imu_sensor_calib: 
  # the transformation (rot. + trans.) of imu frame w.r.t base frame  
  t_imu_base: [0.0, 0.0, 0.0]           # [x y z]
  rpy_imu_base: [3.14159265359, 0, 0]   # [r p y] (see reemc_full_ft_hey5.urdf.xacro)

